### ISSUE TITLE
Nothing is insert, update and fetch with database.

### ISSUE THREAD

**Issue by dharamgoyal** [rmatil/angular-cms#40]
like my rest call is- http://localhost/angular-cms/web/cms/api/users
but it's not getting value from db.....getUsersAction function is not calling in UserController class...

**Comment by rmatil** [comment]
Hi @dharamgoyal 

Thanks for your bug report.

What is probably missing in the README is the fact, that this project requires an Apache Vhost with a document root pointing to `angular-cms/web` (see the example below). Additionally, you may have to add the IP address of your Vhost to your local hosts file.
Furthermore, the module `mod_rewrite` has to be setup. 

After setting this up, you will be able to use the request for users here: 
````
HTTP/1.1 GET cms.dev.localhost/api/users
```

Let me know if you still have any issues.

Cheers


# Example Vhost
```
<VirtualHost *:80>
  ServerName cms.dev.localhost

  ## Vhost docroot
  DocumentRoot "/var/www/web"

  ## Directories, there should at least be a declaration for /var/www/web

  <Directory "/var/www/web">
    Options Indexes FollowSymlinks MultiViews
    AllowOverride All
    Require all granted

    <FilesMatch "\.php$">
      Require all granted
      SetHandler proxy:fcgi://127.0.0.1:9000

    </FilesMatch>

  </Directory>

  ## Logging
  ErrorLog "/var/log/apache2/av_7apho8ch9ykw_error.log"
  ServerSignature Off
  CustomLog "/var/log/apache2/av_7apho8ch9ykw_access.log" combined

  ## Server aliases
  ServerAlias www.cms.dev.localhost

  ## SetEnv/SetEnvIf for environment variables
  SetEnv APP_ENV dev
</VirtualHost>
```

**Comment by rmatil** [comment]
I will close this issue for now, but if you have any further problems, feel free to reopen or creating a new one.
